[theme]
# Primary accent for interactive elements
primaryColor = "#575fe8"

# Background color for the main content area
backgroundColor = "#34A5E5"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#34A5E5"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
